[project]
name = "knowledge-admin"
version = "1.0.0"
description = "Knowledge backend"
requires-python = ">=3.13"
dependencies = [
    "knowledge-common==1.0.0",
    # admin 专属
    "alembic==1.18.3",
    "pillow==12.1.1",
    "textual==8.2.5",
    # 开发工具（建议后续移至 dependency-groups.dev）
    "ruff==0.15.0",
]

#[build-system]
#requires = ["setuptools"]
#build-backend = "setuptools.build_meta"

#[project.scripts]
#ruoyi = "cli.main:main"
#
#[tool.uv]
#package = false

#[tool.setuptools.packages.find]
#include = ["cli*"]

[tool.hatch.build.targets.wheel]
packages = ["src/knowledge_admin"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = true
